# Generated by Django 4.2.3 on 2023-07-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SangreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azucar_porcentaje', models.FloatField()),
                ('grasa_porcentaje', models.FloatField()),
                ('oxygen_porcentaje', models.FloatField()),
                ('nivel_riesgo', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
